import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';
import "./globals.css";
import Heddder from "./component/Context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col`}>
        <div className="flex-1 flex flex-col  w-full">
          <Heddder>
            {children}
          </Heddder>
        </div>
        <footer className="bg-gray-800 text-white w-full text-center mb-0 py-5">
          <span>&copy; 2025 Eassy Larning. All rights reserved.</span>
        </footer>
      </body>
    </html>
  );
}